language: objective-c
script: 
- xcodebuild -target PQXMLParserFramework -project PQXMLParser.xcodeproj;
- xcodebuild -target Framework -project PQXMLParser.xcodeproj;
- xcodebuild test -project PQXMLParser.xcodeproj -scheme PQXMLParser -destination 'platform=iOS Simulator,name=iPhone 5s';