language: objective-c
osx_image: xcode8.3
xcode_project: PQXMLParser.xcodeproj
xcode_scheme: PQXMLParserTests
xcode_sdk: iphonesimulator10.3

script:
 - xcodebuild clean build -sdk iphonesimulator -workspace PQXMLParser.xcodeproj -scheme PQXMLParserTests CODE_SIGNING_REQUIRED=NO